"use client";
import {useState} from "react";
type Plan="PLUS"|"FAMILY";type BillingInterval="monthly"|"annual";
type CheckoutButtonProps={plan:Plan;interval?:BillingInterval;label:string;primary?:boolean;busy:string|null;onCheckout:(plan:Plan,interval:BillingInterval)=>void};
function CheckoutButton({plan,interval="monthly",label,primary=false,busy,onCheckout}:CheckoutButtonProps){return <button type="button" onClick={()=>onCheckout(plan,interval)} disabled={busy!==null} className={primary?"bg-[#23392c] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50":"border border-black/25 px-4 py-3 text-sm font-semibold disabled:opacity-50"}>{busy===`${plan}-${interval}`?"Opening checkout…":label}</button>}
export function BillingPlans({currentPlan="PERSONAL",currentProvider}:{currentPlan?:string;currentProvider?:string|null}){
  const [busy,setBusy]=useState<string|null>(null),[error,setError]=useState("");
  async function checkout(plan:Plan,interval:BillingInterval){setBusy(`${plan}-${interval}`);setError("");try{const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,interval})}),body=await response.json() as {url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error??"Checkout could not be started.");window.location.assign(body.url)}catch(cause){setError(cause instanceof Error?cause.message:"Checkout could not be started.");setBusy(null)}}
  async function manage(){setBusy("portal");setError("");try{const response=await fetch("/api/billing/dodo/portal",{method:"POST"}),body=await response.json() as {url?:string;error?:string};if(!response.ok||!body.url)throw new Error(body.error??"Subscription settings could not be opened.");window.location.assign(body.url)}catch(cause){setError(cause instanceof Error?cause.message:"Subscription settings could not be opened.");setBusy(null)}}
  const start=(plan:Plan,interval:BillingInterval)=>void checkout(plan,interval);
  return <div className="mt-4 border-t border-black/15 pt-4">{currentProvider==="dodo"&&currentPlan!=="PERSONAL"?<button type="button" onClick={()=>void manage()} disabled={busy!==null} className="mb-5 border border-black/25 px-4 py-3 text-sm font-semibold disabled:opacity-50">{busy==="portal"?"Opening subscription settings…":"Manage subscription"}</button>:null}<div><p className="text-xs font-semibold">Choose your subscription</p><p className="mt-1 text-xs text-black/45">Pay monthly or save 10% with annual billing. Subscriptions renew automatically until cancelled.</p><div className="mt-3 grid gap-3">{currentPlan!=="PLUS"?<div className="flex flex-wrap gap-3"><CheckoutButton plan="PLUS" label="Plus · $8/month" primary busy={busy} onCheckout={start}/><CheckoutButton plan="PLUS" interval="annual" label="Plus · $86.40/year · save 10%" busy={busy} onCheckout={start}/></div>:null}{currentPlan!=="FAMILY"?<div className="flex flex-wrap gap-3"><CheckoutButton plan="FAMILY" label="Family · $14/month" busy={busy} onCheckout={start}/><CheckoutButton plan="FAMILY" interval="annual" label="Family · $151.20/year · save 10%" busy={busy} onCheckout={start}/></div>:null}</div></div>{error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}</div>;
}
