"use client";
import {FormEvent,useState} from "react";

type Medication={name:string;dosage:string|null;schedule:string|null;reason:string|null;prescriber:string|null;refillDate:string|null;expirationDate:string|null;sourcePage:number|null;confidence:number};
type Extraction={documentType:string;summary:string;documentDate:string|null;provider:string|null;facility:string|null;facts:{label:string;value:string;sourcePage:number|null;confidence:number}[];followUpItems:{instruction:string;sourcePage:number|null}[];timelineDraft:{title:string;description:string;occurredOn:string|null};medications:Medication[];warnings:string[]};

export function DocumentExtractionReview({extractionId,extraction}:{extractionId:string;extraction:Extraction}){
  return <section className="border-t border-black/15 bg-[#eee4d8] p-5"><p className="text-xs font-semibold uppercase tracking-[.12em]">AI-organized draft · verify against the original</p><h3 className="mt-3 text-xl font-semibold">Document overview</h3><p className="mt-2 max-w-4xl text-sm leading-6 text-black/65">{extraction.summary}</p><dl className="mt-5 grid border border-black/15 bg-[#faf9f5] sm:grid-cols-3">{[["Document date",extraction.documentDate],["Provider",extraction.provider],["Facility",extraction.facility]].map(([label,value])=><div key={label} className="border-b border-black/10 p-4 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><dt className="text-[10px] font-semibold uppercase tracking-[.12em] text-black/40">{label}</dt><dd className="mt-2 text-sm">{value||"Not identified"}</dd></div>)}</dl>{extraction.facts.length?<div className="mt-5"><h3 className="font-semibold">Facts found in the document</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{extraction.facts.map((fact,index)=><article key={`${fact.label}-${index}`} className="border border-black/15 bg-[#faf9f5] p-4"><div className="flex items-start justify-between gap-3"><h4 className="text-sm font-semibold">{fact.label}</h4><span className="shrink-0 text-[10px] text-black/35">{fact.sourcePage?`Page ${fact.sourcePage} · `:""}{Math.round(fact.confidence*100)}%</span></div><p className="mt-2 text-sm leading-6 text-black/60">{fact.value}</p></article>)}</div></div>:null}{extraction.followUpItems.length?<div className="mt-5 border-l-2 border-[#9a6a48] bg-[#faf9f5] p-4"><h3 className="text-sm font-semibold">Follow-up written in the document</h3>{extraction.followUpItems.map((item,index)=><p key={index} className="mt-2 text-sm leading-6 text-black/60">{item.instruction}{item.sourcePage?` · Page ${item.sourcePage}`:""}</p>)}</div>:null}{extraction.warnings.map((warning,index)=><p key={index} className="mt-2 text-xs text-[#7a4b2f]">{warning}</p>)}<TimelineReview extractionId={extractionId} draft={extraction.timelineDraft}/>{extraction.medications.length?<div className="mt-6"><h3 className="font-semibold">Medication details found</h3><div className="mt-3 grid gap-4">{extraction.medications.map((medication,index)=><MedicationReview key={`${medication.name}-${index}`} extractionId={extractionId} index={index} medication={medication}/>)}</div></div>:null}<p className="mt-5 text-xs leading-5 text-black/45">LifeLens organizes visible facts; it does not verify findings, diagnose conditions, interpret clinical significance, or provide medical advice.</p></section>;
}

function TimelineReview({extractionId,draft}:{extractionId:string;draft:Extraction["timelineDraft"]}){
  const [busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");
  async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/ai/documents/confirm-timeline",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({extractionId,...values})});const body=await response.json();if(!response.ok)throw new Error(body.error??"The timeline entry could not be saved.");setSaved(true)}catch(cause){setError(cause instanceof Error?cause.message:"The timeline entry could not be saved.")}finally{setBusy(false)}}
  return <form onSubmit={confirm} className="mt-6 border border-black/20 bg-[#faf9f5] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-black/40">Suggested record</p><h3 className="mt-1 font-semibold">Add this document to your timeline</h3></div><span className="text-xs text-black/40">Nothing is saved automatically</span></div><div className="mt-4 grid gap-3 md:grid-cols-[1fr_180px]"><Field name="title" label="Timeline title" value={draft.title}/><Field name="occurredOn" label="Date" value={draft.occurredOn??""} type="date"/></div><label className="mt-3 block text-xs font-semibold">Description<textarea required name="description" defaultValue={draft.description} className="mt-1 min-h-24 w-full border border-black/20 bg-white p-3 text-sm font-normal"/></label><button disabled={busy||saved} className="mt-4 bg-[#23392c] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saved?"Added to timeline":busy?"Adding…":"Confirm and add to timeline"}</button>{error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}</form>;
}

function MedicationReview({extractionId,index,medication}:{extractionId:string;index:number;medication:Medication}){const [busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState("");async function confirm(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const medicationValues=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/ai/documents/confirm",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({extractionId,medicationIndex:index,medication:medicationValues})});const body=await response.json();if(!response.ok)throw new Error(body.error??"The medication could not be saved.");setSaved(true)}catch(cause){setError(cause instanceof Error?cause.message:"The medication could not be saved.")}finally{setBusy(false)}}return <form onSubmit={confirm} className="border border-black/20 bg-[#faf9f5] p-4"><div className="mb-4 flex items-center justify-between gap-3"><b>Review medication</b><span className="text-xs text-black/40">Page {medication.sourcePage??"unknown"} · {Math.round(medication.confidence*100)}%</span></div><div className="grid gap-3 md:grid-cols-3"><Field name="name" label="Medication" value={medication.name}/><Field name="dosage" label="Dosage" value={medication.dosage??""}/><Field name="schedule" label="Schedule" value={medication.schedule??""}/><Field name="reason" label="Reason" value={medication.reason??""}/><Field name="prescriber" label="Prescriber" value={medication.prescriber??""}/><Field name="refillDate" label="Refill date" value={medication.refillDate??""} type="date"/><Field name="expirationDate" label="Expiration date" value={medication.expirationDate??""} type="date"/></div><button disabled={busy||saved} className="mt-4 bg-[#23392c] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saved?"Added to Medicine Cabinet":busy?"Adding…":"Confirm and add medication"}</button>{error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}</form>}

function Field({name,label,value,type="text"}:{name:string;label:string;value:string;type?:string}){return <label className="text-xs font-semibold">{label}<input required={["title","occurredOn","name","dosage","schedule"].includes(name)} name={name} type={type} defaultValue={value} className="mt-1 h-10 w-full border border-black/20 bg-white px-3 text-sm font-normal"/></label>}
