"use client";
import {FormEvent,useState} from "react";
import {Archive,Clipboard,Plus,RotateCcw,Share2,Trash2} from "lucide-react";

export type ManagedHelpBoard={id:string;slug:string;label:string;archivedAt:string|null;createdAt:string};
export function HelpBoardManager({initialBoards,defaultLabel}:{initialBoards:ManagedHelpBoard[];defaultLabel:string}){
  const [boards,setBoards]=useState(initialBoards),[label,setLabel]=useState(defaultLabel),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  async function createBoard(event:FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/help/boards",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({label})});const json=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(json.error??"Could not create the board.");return}setBoards(current=>[json.board,...current]);setMessage("Board created. Share the link when you’re ready.")}
  function boardUrl(slug:string){return `${window.location.origin}/help/${slug}`}
  async function share(board:ManagedHelpBoard){const url=boardUrl(board.slug);try{if(navigator.share)await navigator.share({title:board.label,text:"Join our LifeLens Help Circle—no account needed.",url});else{await navigator.clipboard.writeText(url);setMessage("Link copied.")}}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return;setMessage("Could not share the link.")}}
  async function copy(board:ManagedHelpBoard){await navigator.clipboard.writeText(boardUrl(board.slug));setMessage("Link copied.")}
  async function update(board:ManagedHelpBoard,action:"archive"|"restore"){const response=await fetch(`/api/help/boards/${board.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action})});if(response.ok)setBoards(current=>current.map(x=>x.id===board.id?{...x,archivedAt:action==="archive"?new Date().toISOString():null}:x));else setMessage("Could not update the board.")}
  async function remove(board:ManagedHelpBoard){if(!window.confirm(`Delete “${board.label}” and all its tasks and updates?`))return;const response=await fetch(`/api/help/boards/${board.id}`,{method:"DELETE"});if(response.ok)setBoards(current=>current.filter(x=>x.id!==board.id));else setMessage("Could not delete the board.")}
  return <section className="mt-6 border border-black/20 bg-[#faf9f5]">
    <header className="border-b border-black/15 p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-black/40">No-login coordination</p><h2 className="mt-1 text-xl font-semibold">Help Circle</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-black/55">Share errands, rides, meals, and visits with trusted helpers. Anyone with the link can participate without a LifeLens account.</p></header>
    <form onSubmit={createBoard} className="grid gap-3 border-b border-black/15 p-5 sm:grid-cols-[1fr_auto]"><label className="text-sm font-semibold">Board name<input value={label} onChange={e=>setLabel(e.target.value)} required maxLength={80} className="mt-2 h-11 w-full border border-black/20 bg-white px-3 font-normal"/></label><button disabled={busy} className="self-end bg-[#23392c] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><Plus className="mr-2 inline" size={16}/>{busy?"Creating…":"Create a Help Board"}</button></form>
    {message?<p role="status" className="mx-5 mt-4 bg-[#eef1e9] px-4 py-3 text-sm text-[#23392c]">{message}</p>:null}
    <div className="grid gap-4 p-5 lg:grid-cols-2">{boards.length?boards.map(board=><article key={board.id} className={`border p-4 ${board.archivedAt?"border-black/10 bg-black/[.025] opacity-70":"border-black/20 bg-white"}`}><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold">{board.label}</h3><p className="mt-1 text-xs text-black/45">{board.archivedAt?"Archived · public link disabled":"Active · no login required"}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{!board.archivedAt?<><button onClick={()=>copy(board)} className="border border-black/20 px-3 py-2 text-xs font-semibold"><Clipboard className="mr-1.5 inline" size={14}/>Copy link</button><button onClick={()=>share(board)} className="border border-black/20 px-3 py-2 text-xs font-semibold"><Share2 className="mr-1.5 inline" size={14}/>Share</button></>:null}<button onClick={()=>update(board,board.archivedAt?"restore":"archive")} className="border border-black/20 px-3 py-2 text-xs font-semibold">{board.archivedAt?<RotateCcw className="mr-1.5 inline" size={14}/>:<Archive className="mr-1.5 inline" size={14}/>} {board.archivedAt?"Restore":"Archive"}</button><button onClick={()=>remove(board)} className="border border-red-900/20 px-3 py-2 text-xs font-semibold text-red-800"><Trash2 className="mr-1.5 inline" size={14}/>Delete</button></div></article>):<p className="text-sm text-black/45">No help boards yet. Create one when there’s something the circle can coordinate.</p>}</div>
  </section>
}
