"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";

type Profile={full_name:string;birth_date:string|null;height_cm:number|null;weight_kg:number|null;goals:string[];conditions:string[];emergency_contact:string|null;primary_doctor:string|null;preferred_language:string;timezone:string};
const goalOptions=["Stay active","Remember my history","Prepare for appointments","Keep family informed"];

export function ProfileSettingsForm({profile}:{profile:Profile}){
  const router=useRouter(),[goals,setGoals]=useState(profile.goals??[]),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");setError("");const values=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:values.name,birthDate:values.birthDate,heightCm:values.heightCm?Number(values.heightCm):undefined,weightKg:values.weightKg?Number(values.weightKg):undefined,goals,conditions:values.conditions,emergencyContact:values.emergencyContact,primaryDoctor:values.primaryDoctor,preferredLanguage:values.preferredLanguage,timezone:values.timezone})});const result=await response.json().catch(()=>null) as {error?:string}|null;if(!response.ok){setError(result?.error??"We couldn’t update your information.");setBusy(false);return}setMessage("Your information has been updated.");setBusy(false);router.refresh()}
  return <section className="mb-6 border border-black/20 bg-[#faf9f5] p-5"><div className="border-b border-black/15 pb-4"><h2 className="font-semibold">Personal information</h2><p className="mt-1 text-sm text-black/50">Update the details LifeLens uses across your dashboard, health summaries, and family circle.</p></div><form onSubmit={submit} className="mt-5 grid gap-5 sm:grid-cols-2">
    <Field name="name" label="Full name" defaultValue={profile.full_name} required/><Field name="birthDate" label="Date of birth" type="date" defaultValue={profile.birth_date??""}/><Field name="heightCm" label="Height (cm)" type="number" defaultValue={profile.height_cm??""}/><Field name="weightKg" label="Weight (kg)" type="number" defaultValue={profile.weight_kg??""}/><Field name="conditions" label="Existing conditions" defaultValue={(profile.conditions??[]).join(", ")} placeholder="Separate multiple items with commas"/><Field name="primaryDoctor" label="Primary doctor" defaultValue={profile.primary_doctor??""}/><Field name="emergencyContact" label="Emergency contact" defaultValue={profile.emergency_contact??""}/><label className="text-sm font-semibold">Language<select name="preferredLanguage" defaultValue={profile.preferred_language??"en"} className="mt-2 h-12 w-full border border-black/20 bg-white px-3 font-normal"><option value="en">English</option><option value="sw">Kiswahili</option><option value="fr">French</option></select></label><Field name="timezone" label="Timezone" defaultValue={profile.timezone??"UTC"} required/>
    <fieldset className="sm:col-span-2"><legend className="text-sm font-semibold">Primary goals</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{goalOptions.map(goal=><label key={goal} className="flex items-center gap-3 border border-black/15 bg-white p-3 text-sm"><input type="checkbox" checked={goals.includes(goal)} onChange={()=>setGoals(current=>current.includes(goal)?current.filter(item=>item!==goal):[...current,goal])}/>{goal}</label>)}</div></fieldset>
    <div className="sm:col-span-2"><button disabled={busy} className="bg-[#23392c] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save changes"}</button>{message?<p role="status" className="mt-3 text-sm text-green-800">{message}</p>:null}{error?<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>:null}</div>
  </form></section>
}
function Field({name,label,type="text",defaultValue,placeholder,required}:{name:string;label:string;type?:string;defaultValue:string|number;placeholder?:string;required?:boolean}){return <label className="text-sm font-semibold">{label}<input name={name} type={type} defaultValue={defaultValue} placeholder={placeholder} required={required} className="mt-2 h-12 w-full border border-black/20 bg-white px-3 font-normal outline-none focus:border-[#23392c]"/></label>}
