"use client";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Check,Clipboard,Plus,Share2} from "lucide-react";

type Task={id:string;title:string;details:string|null;dueAt:string|null;claimedBy:string|null;claimedAt:string|null;createdAt:string};
type Update={id:string;authorName:string;body:string;createdAt:string};
export type PublicHelpBoardData={id:string;label:string;slug:string;tasks:Task[];updates:Update[]};

function savedName(){if(typeof window==="undefined")return "";try{return localStorage.getItem("lifelens-help-name")??""}catch{return ""}}
export function PublicHelpBoard({initialBoard}:{initialBoard:PublicHelpBoardData}){
  const [board,setBoard]=useState(initialBoard),[name,setName]=useState(savedName),[showTask,setShowTask]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const refresh=useCallback(async()=>{const response=await fetch(`/api/help/${board.slug}`,{cache:"no-store"});if(response.ok){const json=await response.json();setBoard(json.board)}},[board.slug]);
  useEffect(()=>{const timer=window.setInterval(refresh,4000);return()=>window.clearInterval(timer)},[refresh]);
  function rememberName(value:string){setName(value);try{localStorage.setItem("lifelens-help-name",value)}catch{/* Private browsers may block storage; the flow still works. */}}
  async function submit(path:string,body:Record<string,unknown>){setBusy(true);setMessage("");const response=await fetch(`/api/help/${board.slug}/${path}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));setBusy(false);if(!response.ok){setMessage(json.error??"Something went wrong.");return false}await refresh();return true}
  async function claim(taskId:string){if(!name.trim()){setMessage("Add your name below first, so everyone knows who has it.");document.getElementById("helper-name")?.focus();return}await submit("claim",{taskId,name})}
  async function addTask(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);if(await submit("tasks",{title:data.get("title"),details:data.get("details"),dueAt:data.get("dueAt")})){form.reset();setShowTask(false)}}
  async function addUpdate(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);if(await submit("updates",{name,body:data.get("body")}))form.reset()}
  async function share(){const url=window.location.href;try{if(navigator.share)await navigator.share({title:board.label,text:"Join our LifeLens Help Circle—no account needed.",url});else{await navigator.clipboard.writeText(url);setMessage("Link copied.")}}catch(error){if(!(error instanceof DOMException&&error.name==="AbortError"))setMessage("Could not share the link.")}}
  return <main className="min-h-screen bg-[#f7f4ed] text-[#243028]"><div className="mx-auto max-w-6xl px-5 pb-16 pt-8 sm:px-8 sm:pt-12">
    <header className="border-b border-black/15 pb-8"><div className="flex items-center justify-between gap-4"><a href="/" className="text-lg font-bold tracking-[-.04em]">LifeLens</a><button onClick={share} className="border border-black/20 bg-[#faf9f5] px-3 py-2 text-sm font-semibold"><Share2 className="mr-2 inline" size={16}/>Share board</button></div><p className="mt-12 text-xs font-semibold uppercase tracking-[.16em] text-black/40">Help Circle</p><h1 className="serif mt-3 max-w-3xl text-4xl leading-tight tracking-[-.035em] sm:text-6xl">{board.label}</h1><p className="mt-4 max-w-xl text-base leading-7 text-black/55">A shared task board. No account needed—just claim what you can help with.</p></header>
    <section className="py-8"><div className="flex items-center justify-between gap-4"><h2 className="text-xs font-bold uppercase tracking-[.16em] text-black/45">Tasks</h2><button onClick={()=>setShowTask(value=>!value)} className="bg-[#23392c] px-4 py-2.5 text-sm font-semibold text-white"><Plus className="mr-1.5 inline" size={16}/>Add a task</button></div>
      {showTask?<form onSubmit={addTask} className="mt-5 grid gap-3 border border-black/20 bg-[#faf9f5] p-4 sm:grid-cols-2"><label className="text-sm font-semibold">What needs doing?<input name="title" required maxLength={120} className="mt-2 h-11 w-full border border-black/20 bg-white px-3 font-normal"/></label><label className="text-sm font-semibold">When? <span className="font-normal text-black/40">Optional</span><input name="dueAt" type="datetime-local" className="mt-2 h-11 w-full border border-black/20 bg-white px-3 font-normal"/></label><label className="text-sm font-semibold sm:col-span-2">A little more detail <span className="font-normal text-black/40">Optional</span><textarea name="details" maxLength={500} rows={3} className="mt-2 w-full border border-black/20 bg-white p-3 font-normal"/></label><button disabled={busy} className="justify-self-start bg-[#23392c] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Add task</button></form>:null}
      <div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{board.tasks.length?board.tasks.map(task=><article key={task.id} className={`flex min-h-52 flex-col border p-5 transition-colors duration-300 ${task.claimedBy?"border-[#9aaa8e] bg-[#e8eee3]":"border-black/20 bg-[#faf9f5]"}`}><p className="text-xs font-semibold uppercase tracking-[.1em] text-black/40">{task.dueAt?new Date(task.dueAt).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}):"Whenever you can"}</p><h3 className="mt-3 text-xl font-semibold leading-snug">{task.title}</h3>{task.details?<p className="mt-2 text-sm leading-6 text-black/55">{task.details}</p>:null}<div className="mt-auto pt-5">{task.claimedBy?<p className="flex items-center gap-2 text-sm font-semibold text-[#36513d]"><span className="grid size-6 place-items-center rounded-full bg-[#36513d] text-white"><Check size={14}/></span>Covered by {task.claimedBy}</p>:<button disabled={busy} onClick={()=>claim(task.id)} className="w-full border border-[#23392c] px-4 py-3 text-sm font-semibold text-[#23392c] hover:bg-[#23392c] hover:text-white">I’ve got it</button>}</div></article>):<p className="text-sm text-black/45">Nothing on the list yet. That’s either excellent news—or someone should add the groceries.</p>}</div>
    </section>
    <section className="grid gap-8 border-t border-black/15 py-8 lg:grid-cols-[1fr_1.5fr]"><div><h2 className="text-xs font-bold uppercase tracking-[.16em] text-black/45">Your name</h2><label className="mt-4 block text-sm text-black/55" htmlFor="helper-name">Saved only on this device<input id="helper-name" value={name} onChange={e=>rememberName(e.target.value)} maxLength={60} placeholder="e.g. Sarah" className="mt-2 h-12 w-full border border-black/20 bg-[#faf9f5] px-3 text-black"/></label></div><div><h2 className="text-xs font-bold uppercase tracking-[.16em] text-black/45">Updates</h2><form onSubmit={addUpdate} className="mt-4 flex gap-2"><input name="body" required maxLength={500} placeholder="Post an update…" className="h-12 min-w-0 flex-1 border border-black/20 bg-[#faf9f5] px-3"/><button disabled={busy||!name.trim()} className="bg-[#23392c] px-4 text-sm font-semibold text-white disabled:opacity-40">Post</button></form>{message?<p role="status" className="mt-3 text-sm text-[#8b4b3d]">{message}</p>:null}<div className="mt-5 divide-y divide-black/10">{board.updates.map(update=><article key={update.id} className="py-4"><p className="text-xs text-black/40"><strong className="text-black/65">{update.authorName}</strong> · {new Intl.RelativeTimeFormat(undefined,{numeric:"auto"}).format(-Math.max(0,Math.round((Date.now()-new Date(update.createdAt).getTime())/3600000)),"hour")}</p><p className="mt-2 text-sm leading-6">{update.body}</p></article>)}</div></div></section>
    <footer className="border border-[#c9bfae] bg-[#eee9de] p-5 text-sm leading-6 text-black/60"><Clipboard className="mr-2 inline align-text-bottom" size={17}/><strong className="text-black/75">Keep health details in LifeLens.</strong> This board is for coordinating help, not storing medical information. Only share this link with people you trust.</footer>
  </div></main>
}
