import DodoPayments from "dodopayments";
export type PaidPlan="PLUS"|"FAMILY";

export type DodoEnvironment="test_mode"|"live_mode";
export type BillingInterval="monthly"|"annual";
export function dodoEnvironment():DodoEnvironment{return process.env.DODO_PAYMENTS_ENVIRONMENT==="test_mode"?"test_mode":"live_mode"}
export function dodoProductId(plan:PaidPlan,interval:BillingInterval){const ids={PLUS:{monthly:process.env.DODO_PLUS_PRODUCT_ID,annual:process.env.DODO_PLUS_ANNUAL_PRODUCT_ID},FAMILY:{monthly:process.env.DODO_FAMILY_PRODUCT_ID,annual:process.env.DODO_FAMILY_ANNUAL_PRODUCT_ID}};const id=ids[plan][interval]?.trim();if(!id)throw new Error("DODO_PRODUCT_NOT_CONFIGURED");return id}
export function dodoPlanForProduct(productId:string,products={PLUS_MONTHLY:process.env.DODO_PLUS_PRODUCT_ID,PLUS_ANNUAL:process.env.DODO_PLUS_ANNUAL_PRODUCT_ID,FAMILY_MONTHLY:process.env.DODO_FAMILY_PRODUCT_ID,FAMILY_ANNUAL:process.env.DODO_FAMILY_ANNUAL_PRODUCT_ID}):PaidPlan|null{if((products.PLUS_MONTHLY&&productId===products.PLUS_MONTHLY)||(products.PLUS_ANNUAL&&productId===products.PLUS_ANNUAL))return "PLUS";if((products.FAMILY_MONTHLY&&productId===products.FAMILY_MONTHLY)||(products.FAMILY_ANNUAL&&productId===products.FAMILY_ANNUAL))return "FAMILY";return null}
export function dodoSubscriptionStatus(status:string){return({active:"ACTIVE",on_hold:"PAST_DUE",paused:"PAUSED",cancelled:"CANCELLED",failed:"FAILED",expired:"EXPIRED",pending:"PENDING"} as Record<string,string>)[status]??"PENDING"}
export function dodoClient(){const bearerToken=process.env.DODO_PAYMENTS_API_KEY?.trim();if(!bearerToken)throw new Error("DODO_NOT_CONFIGURED");return new DodoPayments({bearerToken,webhookKey:(process.env.DODO_PAYMENTS_WEBHOOK_KEY||process.env.DODO_PAYMENTS_WEBHOOK_SECRET)?.trim(),environment:dodoEnvironment(),timeout:20_000,maxRetries:1})}
export async function initializeDodoCheckout(input:{plan:PaidPlan;interval:BillingInterval;userId:string;email:string;name:string}){const origin=new URL(process.env.NEXT_PUBLIC_APP_URL??"http://localhost:3000").origin;const session=await dodoClient().checkoutSessions.create({product_cart:[{product_id:dodoProductId(input.plan,input.interval),quantity:1}],customer:{email:input.email,name:input.name},metadata:{lifelens_user_id:input.userId,lifelens_plan:input.plan,lifelens_interval:input.interval},return_url:`${origin}/billing/return?provider=dodo`,cancel_url:`${origin}/settings`,minimal_address:true});if(!session.checkout_url)throw new Error("DODO_CHECKOUT_FAILED");return session.checkout_url}
