export type Guide={slug:string;title:string;description:string;eyebrow:string;readTime:string;intro:string;takeaways:string[];sections:{heading:string;paragraphs?:string[];bullets?:string[]}[];sources:{title:string;url:string}[]};

export const guides:Guide[]=[
  {slug:"how-to-organize-medical-records",title:"How to organize your medical records",description:"A practical system for gathering, sorting, updating, and securely storing medical records from different doctors, hospitals, laboratories, and portals.",eyebrow:"Health record basics",readTime:"7 minute read",intro:"A useful medical record is not simply a folder full of files. It is a small, maintained system that helps you find the right fact, document, or date when you need it.",takeaways:["Start with a one-page health summary before filing every document.","Keep original files and add dates, providers, and categories instead of renaming information into ambiguity.","Review the record after appointments, medication changes, tests, hospital visits, and changes in emergency contacts."],sections:[
    {heading:"1. Gather records from every source",paragraphs:["Make a source list before downloading anything. Include primary care, specialists, hospitals, laboratories, imaging centers, pharmacies, insurers, paper folders, email attachments, and patient portals.","Download copies when a portal allows it. A portal may show only the information held by that organization, so records from one clinic should not be assumed to represent your complete history."],bullets:["Visit and discharge summaries","Laboratory and imaging reports","Medication and allergy lists","Immunization records","Procedure and surgery notes","Insurance and billing documents","Advance directives and emergency contacts"]},
    {heading:"2. Build a short health summary",paragraphs:["Create a summary that points into the larger archive. Include identifying information, emergency contacts, allergies, current medications, current conditions, major procedures, recent tests, and the names of regular providers.","Record the source and last-updated date. If a detail is uncertain, label it for verification rather than guessing. A personal record should make uncertainty visible."],bullets:["Medicine name, strength, dose, schedule, and reason","Allergy or adverse reaction and what happened","Major illness, operation, or hospitalization with approximate date","Provider, specialty, facility, and contact information"]},
    {heading:"3. Use a predictable filing structure",paragraphs:["Choose categories that match how you search. A simple structure—appointments, medications, laboratory, imaging, procedures, insurance, and emergency information—is usually easier to maintain than dozens of folders.","Use dates in YYYY-MM-DD order, followed by the facility and document type. Keep the original document intact and put your own notes in a separate field so the clinical record is not accidentally altered."]},
    {heading:"4. Keep a timeline, not only folders",paragraphs:["A timeline answers a different question from a folder: what happened before and after this event? Add major visits, new or stopped medications, procedures, test dates, and hospital stays in chronological order.","Do not interpret a result yourself in the timeline. Record what the document says, where it came from, and where the original can be found."]},
    {heading:"5. Protect and maintain the record",paragraphs:["Use a strong unique password and multifactor authentication where available. Limit shared access, remove access that is no longer needed, and avoid placing a complete medical archive behind a public QR code.","Keep an export or backup you can recover independently. Update the summary when something changes and perform a scheduled review at least occasionally so old medications and contact details are clearly marked rather than silently left current."]}
  ],sources:[{title:"MedlinePlus: Personal Health Records",url:"https://medlineplus.gov/personalhealthrecords.html"},{title:"CMS: Personal Health Records",url:"https://www.cms.gov/priorities/key-initiatives/e-health/personal-records"}]},
  {slug:"what-to-bring-to-doctor-appointment",title:"What to bring to a doctor appointment",description:"A practical appointment checklist covering medications, symptoms, questions, records, accessibility needs, and follow-up notes.",eyebrow:"Doctor visit preparation",readTime:"6 minute read",intro:"Preparation makes a short appointment easier to use. The goal is not to bring every record you own; it is to bring the information that helps you and the clinician understand what changed, what matters today, and what needs follow-up.",takeaways:["Bring a complete medication and allergy list, including nonprescription products and supplements.","Write a short symptom timeline and put your most important questions first.","Leave with written next steps, including who is responsible and when follow-up should happen."],sections:[
    {heading:"Before the appointment",paragraphs:["Confirm the location, time, purpose of the visit, and any preparation instructions. Ask the office whether you need identification, insurance information, referral documents, forms, fasting, previous images, or home readings.","If you need an interpreter, mobility assistance, communication support, or more time because of hearing, vision, or cognitive needs, contact the office before the visit."],bullets:["Appointment confirmation and office instructions","Identification and insurance information if requested","Relevant referral, discharge, laboratory, or imaging records","Glasses, hearing aids, mobility devices, or communication aids"]},
    {heading:"Bring one current medication list",paragraphs:["List every prescription medicine, over-the-counter medicine, vitamin, herb, and supplement. For each item, include the name, strength, amount taken, schedule, and reason if known.","Include allergies and previous medication reactions. If you are unsure whether the list is accurate, take the labeled containers or ask a pharmacist or clinician to help reconcile it. Do not stop or change a medicine based only on an organizer or app." ]},
    {heading:"Describe the problem as a timeline",paragraphs:["For a new symptom, write when it began, how often it happens, what it feels like, what makes it better or worse, and how it affects daily activities. Include recent changes such as a new medicine, illness, fall, travel, or procedure if relevant.","Be direct about what you are worried about. A concise timeline is often more useful than trying to remember events under pressure."]},
    {heading:"Prioritize your questions",paragraphs:["Put the most important one or two questions first. Ask for plain-language explanations when a term or instruction is unclear. For tests or treatments, ask what the next step is, when results are expected, and whom to contact.","If a trusted person attends, agree beforehand on their role. The patient should lead where possible, and the office may require permission before discussing protected information with someone else."]},
    {heading:"Before you leave",paragraphs:["Repeat the plan in your own words and ask for written instructions. Record medication changes exactly as directed, follow-up dates, tests, referrals, warning signs the clinician wants you to watch for, and the correct contact route for questions.","After the visit, update your record from the written clinical information rather than memory alone. Keep your personal notes distinguishable from the provider’s instructions."]}
  ],sources:[{title:"MedlinePlus: Talking With Your Doctor",url:"https://medlineplus.gov/talkingwithyourdoctor.html"},{title:"National Institute on Aging: Medical Care and Appointments",url:"https://www.nia.nih.gov/health/medical-care-and-appointments"}]},
  {slug:"emergency-medication-list",title:"How to create an emergency medication list",description:"Create a clear, current medication list for emergencies with medicines, dosages, allergies, conditions, contacts, storage needs, and verification dates.",eyebrow:"Emergency preparedness",readTime:"6 minute read",intro:"In an emergency, a medication list should be short enough to scan and detailed enough to identify what you actually take. It is an information aid—not a prescription, treatment plan, or substitute for emergency services.",takeaways:["Include prescriptions, over-the-counter medicines, vitamins, herbs, and supplements.","Record strength, dose, route, schedule, reason, prescriber, pharmacy, allergies, and the date verified.","Keep an accessible paper copy and a protected digital copy, and update both after any change."],sections:[
    {heading:"Start with identity and contacts",bullets:["Full name and date of birth","Primary emergency contact and relationship","Primary clinician and relevant specialists","Usual pharmacy and phone number","Preferred language and communication needs"]},
    {heading:"Record each medicine precisely",paragraphs:["Copy details from the current label or verified clinical list. Similar medicine names and different strengths can create confusion, so avoid entries such as “blood pressure pill” or “one tablet” without the product and strength.","For medicines taken only when needed, record the written directions. Note important storage or equipment needs, such as refrigeration or a delivery device, without changing the instructions."],bullets:["Generic and brand name when available","Strength and dosage form","Amount, route, and time or frequency","Reason it was prescribed, if known","Prescriber and start date, if useful"]},
    {heading:"Add allergies and important context",paragraphs:["List medication allergies or previous serious reactions and describe the reaction when known. Also include current conditions, implanted devices, and medical supply needs that an emergency team may need to know.","Do not label a medicine as an allergy merely because it was ineffective or inconvenient; ask a clinician or pharmacist how it should be documented when uncertain."]},
    {heading:"Verify and date the list",paragraphs:["Write “verified on” with the date and who checked it. Review the list with a pharmacist or clinician, especially after a hospital discharge, new prescription, stopped medicine, dosage change, or change in pharmacy.","Keep discontinued medicines visibly separate or remove them from the active list while preserving history elsewhere. An undated list can be mistaken for current information."]},
    {heading:"Make it available without making everything public",paragraphs:["Keep a paper copy in an agreed location and a copy with the person when appropriate. Trusted contacts should know where it is. A digital emergency card should reveal only the minimum information needed for its purpose.","For disaster readiness, ask a clinician or pharmacist about lawful emergency refills and safe storage. Do not build an extra supply or alter refrigeration based on general online guidance."]}
  ],sources:[{title:"CDC: Prescriptions and Emergency Preparedness",url:"https://www.cdc.gov/prepare-your-health/take-action/prescriptions.html"},{title:"CDC: Medication Safety and Your Health",url:"https://www.cdc.gov/medication-safety/about/index.html"},{title:"National Institute on Aging: Taking Medicines Safely as You Age",url:"https://www.nia.nih.gov/health/medicines-and-medication-management/taking-medicines-safely-you-age"}]},
  {slug:"coordinate-older-adult-health-information",title:"How families can coordinate an older relative’s health information",description:"A consent-first system for coordinating an older adult’s medications, appointments, records, responsibilities, and emergency information across a family.",eyebrow:"Family caregiving",readTime:"8 minute read",intro:"Family coordination works best when it supports the older person’s choices instead of quietly taking control away. Begin with consent, agree on roles, and maintain one reliable source of truth.",takeaways:["Ask what help the older adult wants and document permission before accessing or sharing information.","Choose one primary coordinator while giving every task a named owner and backup.","Use a shared change log for appointments, medication updates, follow-up tasks, and unresolved questions."],sections:[
    {heading:"Begin with the person, not the paperwork",paragraphs:["Ask the older adult what they want help with, who may receive information, and what should remain private. Capacity and preferences can change, so revisit the conversation rather than treating one discussion as permanent consent.","Being a relative does not automatically provide access to medical records or authority to make decisions. Provider release forms, portal proxy access, advance directives, or legal authority may be required depending on the task and jurisdiction."]},
    {heading:"Assign clear roles",paragraphs:["Select one primary point of contact for the medical team if the older adult agrees. Divide operational tasks such as transportation, pharmacy pickup, appointment notes, bills, meals, and home support instead of asking everyone to “keep an eye on things.”"],bullets:["Task owner and backup person","Due date or appointment date","Where the authoritative information is stored","What requires the older adult’s approval","How urgent changes should be communicated"]},
    {heading:"Maintain one shared health summary",paragraphs:["Keep a current summary of medications, allergies, conditions, clinicians, pharmacy, insurance, emergency contacts, recent hospital visits, and upcoming appointments. Mark who verified each change and when.","Family messages are not a medical record. Separate observations—such as appetite or mobility—from confirmed clinical instructions, and link important updates back to the visit note, prescription label, or other source."]},
    {heading:"Use a before, during, and after appointment routine",paragraphs:["Before: collect the older adult’s questions and recent changes. During: let them answer and make decisions wherever possible, take notes with permission, and ask for plain-language written instructions. After: record the plan, assign each follow-up task, and share only with authorized people.","If relatives disagree, return to the older adult’s stated preferences and the documented care plan. Ask the clinical team, social worker, or appropriate legal professional for help when authority or safety is unclear."]},
    {heading:"Prepare for urgent situations",paragraphs:["Agree on who should be called, where the emergency medication list and advance care documents are kept, and who can access the home or accompany the person. Keep emergency information limited and current.","Coordination should also include caregiver capacity. Build backups and respite into the plan so one person is not silently responsible for every task."]}
  ],sources:[{title:"National Institute on Aging: Tips for Caregivers at Doctor Appointments",url:"https://www.nia.nih.gov/health/medical-care-and-appointments/taking-someone-doctors-appointment-tips-caregivers"},{title:"National Institute on Aging: Caregiver Worksheets",url:"https://www.nia.nih.gov/health/caregiving/caregiver-worksheets"},{title:"National Institute on Aging: Advance Care Planning Tips",url:"https://www.nia.nih.gov/health/advance-care-planning/advance-care-planning-and-health-care-decisions-tips-caregivers-and"}]},
  {slug:"personal-health-record-vs-patient-portal",title:"Personal health records versus hospital patient portals",description:"Understand how a personal health record differs from a hospital patient portal, what each contains, who controls it, and why many people use both.",eyebrow:"Health record basics",readTime:"6 minute read",intro:"A patient portal and a personal health record can contain similar information, but they solve different problems. One is usually a window into a provider’s system; the other is a record maintained for the individual across sources.",takeaways:["A patient portal usually reflects one provider organization’s records and services.","A personal health record is maintained for the individual and can combine information from many sources.","Use portals for provider communication and source documents; use a personal record for continuity, organization, and information you add yourself."],sections:[
    {heading:"What is a patient portal?",paragraphs:["A patient portal is a secure website connected to a health care organization. Depending on the provider, it may show visits, discharge summaries, medications, immunizations, allergies, and results. It may also support messages, refill requests, appointments, forms, bills, or insurance information.","The provider controls the underlying clinical system and decides which information and functions appear. If you see several unrelated organizations, you may have several separate portals."]},
    {heading:"What is a personal health record?",paragraphs:["A personal health record, or PHR, is designed to be accessed and managed by the individual. It can combine copies from clinicians with information the person records, such as over-the-counter medicines, family history, home observations, emergency contacts, and life events.","A PHR does not automatically become a provider’s legal medical record. Information entered there may need to be shared and clinically verified before a care team relies on it."]},
    {heading:"The practical differences",bullets:["Control: portals are generally controlled by provider organizations; a PHR is maintained for the individual.","Scope: a portal may cover one health system; a PHR can span multiple systems and personal entries.","Communication: portals may support secure clinical messaging and refills; an independent PHR generally does not replace those channels.","Source of truth: the provider chart documents clinical care; the PHR helps the person organize copies and context.","Continuity: a PHR can remain useful when providers, insurers, or portals change."]},
    {heading:"Use them together",paragraphs:["Download or request useful records from each portal and file them in the personal record with the provider and date. Keep the original document intact. Use the portal for messages, appointments, prescription requests, and instructions from that provider.","Do not assume changes synchronize automatically. If you correct a medication in a personal record, the provider’s chart may still need a separate update, and the reverse may also be true."]},
    {heading:"Check privacy and access",paragraphs:["Before choosing any personal health record service, read its privacy terms, security controls, export options, deletion process, family permissions, and business model. Privacy obligations can differ depending on who operates the service and how it receives information.","Use a unique password, enable multifactor authentication when available, and grant family access only to people and categories the account owner intends to share."]}
  ],sources:[{title:"HealthIT.gov: Health IT and HIE FAQs",url:"https://healthit.gov/health-it-basics/hit-hie-faqs/"},{title:"HealthIT.gov: PHR, EHR, and EMR Differences",url:"https://www.healthit.gov/faq/what-difference-between-personal-health-record-electronic-health-record-and-electronic-medical"},{title:"CMS: Personal Health Records",url:"https://www.cms.gov/priorities/key-initiatives/e-health/personal-records"}]}
];

export function guideBySlug(slug:string){return guides.find(guide=>guide.slug===slug)}
