create table if not exists public.medications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, dosage text not null, schedule text not null, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.appointments (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, provider text, starts_at timestamptz not null, location text, notes text, created_at timestamptz not null default now());
create table if not exists public.check_ins (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, transcript text not null, recorded_at timestamptz not null default now());
create table if not exists public.family_members (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, email text not null, can_view_timeline boolean not null default false, status text not null default 'invited', created_at timestamptz not null default now(), unique(user_id,email));
create table if not exists public.timeline_events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, category text not null, title text not null, description text not null, occurred_at timestamptz not null default now(), source text, created_at timestamptz not null default now());
create table if not exists public.checkout_attempts (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, plan text not null check(plan in ('PLUS','FAMILY')), reference text not null unique, amount numeric(10,2) not null, currency text not null default 'USD', completed_at timestamptz, created_at timestamptz not null default now());
create table if not exists public.subscriptions (user_id uuid primary key references auth.users(id) on delete cascade, provider text not null default 'chapa', plan text not null default 'PERSONAL' check(plan in ('PERSONAL','PLUS','FAMILY')), status text not null default 'PENDING', provider_reference text unique, current_period_end timestamptz, updated_at timestamptz not null default now());
create table if not exists public.billing_webhooks (message_id text primary key, event_type text not null, payload jsonb not null, received_at timestamptz not null default now());

do $$ declare t text; begin foreach t in array array['medications','appointments','check_ins','family_members','timeline_events','checkout_attempts','subscriptions'] loop execute format('alter table public.%I enable row level security',t); execute format('drop policy if exists %I on public.%I',t||'_own',t); execute format('create policy %I on public.%I for all to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id)',t||'_own',t); execute format('grant select, insert, update, delete on public.%I to authenticated',t); end loop; end $$;
revoke all on public.billing_webhooks from anon, authenticated;
create index if not exists medications_user_idx on public.medications(user_id,created_at desc);
create index if not exists appointments_user_idx on public.appointments(user_id,starts_at);
create index if not exists check_ins_user_idx on public.check_ins(user_id,recorded_at desc);
create index if not exists timeline_events_user_idx on public.timeline_events(user_id,occurred_at desc);
