alter table public.family_members add column if not exists member_user_id uuid references auth.users(id) on delete set null;
alter table public.family_members add column if not exists can_contribute boolean not null default true;
update public.family_members fm set member_user_id=u.id,status='accepted' from auth.users u where lower(u.email)=lower(fm.email) and fm.member_user_id is null;
create or replace function public.match_family_invitation() returns trigger language plpgsql security definer set search_path=public,auth as $$ begin select id into new.member_user_id from auth.users where lower(email)=lower(new.email) limit 1; if new.member_user_id is not null then new.status='accepted'; end if; return new; end $$;
drop trigger if exists match_family_invitation_on_write on public.family_members;
create trigger match_family_invitation_on_write before insert or update of email on public.family_members for each row execute function public.match_family_invitation();
create or replace function public.accept_family_invitations() returns trigger language plpgsql security definer set search_path=public,auth as $$ begin update public.family_members set member_user_id=new.id,status='accepted' where lower(email)=lower(new.email) and member_user_id is null; return new; end $$;
drop trigger if exists accept_family_invitations_on_signup on auth.users;
create trigger accept_family_invitations_on_signup after insert on auth.users for each row execute function public.accept_family_invitations();
drop policy if exists "family_members_member_read" on public.family_members;
create policy "family_members_member_read" on public.family_members for select to authenticated using ((select auth.uid()) = member_user_id);
create table if not exists public.family_checkins (id uuid primary key default gen_random_uuid(), owner_id uuid not null references auth.users(id) on delete cascade, author_id uuid not null references auth.users(id) on delete cascade, visit_date date not null default current_date, note text not null, mood text, walking text, appetite text, created_at timestamptz not null default now());
alter table public.family_checkins enable row level security;
drop policy if exists "family_checkins_owner_read" on public.family_checkins;
drop policy if exists "family_checkins_author_read" on public.family_checkins;
drop policy if exists "family_checkins_member_insert" on public.family_checkins;
create policy "family_checkins_owner_read" on public.family_checkins for select to authenticated using ((select auth.uid())=owner_id);
create policy "family_checkins_author_read" on public.family_checkins for select to authenticated using ((select auth.uid())=author_id);
create policy "family_checkins_member_insert" on public.family_checkins for insert to authenticated with check ((select auth.uid())=author_id and exists(select 1 from public.family_members f where f.user_id=owner_id and f.member_user_id=(select auth.uid()) and f.can_contribute));
grant select,insert on public.family_checkins to authenticated;
create table if not exists public.user_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, title text not null, body text not null, href text, read_at timestamptz, created_at timestamptz not null default now());
alter table public.user_notifications enable row level security;
drop policy if exists "notifications_own" on public.user_notifications;
create policy "notifications_own" on public.user_notifications for all to authenticated using ((select auth.uid())=user_id) with check ((select auth.uid())=user_id);
grant select,insert,update,delete on public.user_notifications to authenticated;
